AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - .ruby-version
    - .config.ru

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/ParameterLists:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Lint/AssignmentInCondition:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Documentation:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
